# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'


target 'College' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for College
  pod 'Google-Mobile-Ads-SDK'
  pod 'SnapKit' 
pod 'ImageSlideshow', '~> 1.8'
pod 'ImageSlideshow/SDWebImage'  # Para suporte a imagens remotas


  target 'CollegeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CollegeUITests' do
    # Pods for testing
  end

end
